-- RDBMS 스트림 처리를 위한 SQL 평가 세부 요구사항

-- 1번
CREATE TABLE MY_MEMBER(
	MEM_NUM INT PRIMARY KEY
	,MEM_ID VARCHAR(15) NOT NULL
	,MEM_PW VARCHAR(20) NOT NULL
	,MEM_NAME VARCHAR(13) NOT NULL
	,MEM_AGE INT
	,EMAIL VARCHAR(30)
);

-- 2번
INSERT INTO MY_MEMBER(MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, MEM_AGE, EMAIL)
VALUES(1,'PYTHON','JAVA24','김파이썬',23,'PYTHON@GMAIL.COM');
INSERT INTO MY_MEMBER(MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, MEM_AGE, EMAIL)
VALUES(2,'JOHNNY SUH','CHICAGO95','서영호',29,'JOHNNYSUH@GMAIL.COM');

-- 3번
UPDATE MY_MEMBER
SET
	MEM_NAME = '김자바'
	, MEM_ID = 'KIMJAVA'
WHERE MEM_NUM = 1;

SELECT * FROM MY_MEMBER;

-- 4번 : 수정해야함 꼭 다시 보기
SELECT EMPNO, ENAME, SAL, COMM
FROM emp E, dept D 
WHERE E.DEPTNO = D.DEPTNO 
AND SAL >= 300
AND SAL < 5000;

-- 5번
-- 6번 : 아직 못 푸는 문제
-- 7번
-- 8번 : 못 푸는 문제
-- 9번
-- 10번