CREATE TABLE ITEM_INFO (
 ITEM_NUM INT AUTO_INCREMENT PRIMARY KEY-- 상품번호
, ITEM_NAME VARCHAR(50) NOT NULL-- 상품명
, ITEM_PRICE INT NOT NULL-- 상품가격
, SELLER VARCHAR(30) NOT NULL-- 판매자
, ITEM_INTRO VARCHAR(100)-- 상품 설명
, REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 );
 
 CREATE TABLE ORDER_INFO (
 ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY-- 주문번호
, BUY_ITEM_NAME VARCHAR(50)-- 구매 상품명
, BUY_ITEM_PRICE INT-- 구매 상품 단가
, BUYER VARCHAR(50) NOT NULL-- 구매자
, BUY_CNT INT-- 구매 수량
, BUY_PRICE INT-- 구매 가격 (단가 * 수량)
 , BUY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 );