 CREATE TABLE ORDER_INFO (
 ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY-- 주문번호
, BUY_ITEM_NAME VARCHAR(50)-- 구매 상품명
, BUY_ITEM_PRICE INT-- 구매 상품 단가
, BUYER VARCHAR(50) NOT NULL-- 구매자
, BUY_CNT INT-- 구매 수량
, BUY_PRICE INT-- 구매 가격 (단가 * 수량)
 , BUY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 );