-- 2024.6.27

CREATE TABLE SCORE_INFO (
	STU_NUM INT PRIMARY KEY
	, STU_NAME VARCHAR(50)
	, KOR_SCORE INT
	, ENG_SCORE INT
	, INTRO VARCHAR(100)
);

INSERT INTO score_info 
VALUES (1, '홍길동', 80, 90, '반가워요');

SELECT * FROM score_info;

SELECT STU_NUM
	, STU_NAME
 	, KOR_SCORE
	, ENG_SCORE
 	, INTRO
 FROM score_info
 WHERE STU NUM = 82;
